pool:
  name: 'infrastructure-agents'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker.artifacts.karops.io'
    repository: 'poc/examples/welcome'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
